### ISSUE TITLE
Copying Classes, Quizzes, and Questions

### ISSUE THREAD

**Issue by sguthals** [sguthals/OSF#11]
Consider copy class, quiz, question.

**Comment by stevoleeto** [comment]
Potential Features needed and simple examples of how they could be implemented:

The following could be implemented with a "share" button which could just pop out a unique code (the database id?) which they could then send to other teachers to share the respective object.
- Teacher choosing to share classroom
- Teacher choosing to share quiz
- Teacher choosing to share question

The following could be implemented with a "add by code" button which depending on the current view, would copy and add the object to the current teacher.
- Teacher choosing to add a copied classroom
- Teacher choosing to add a copied quiz
- Teacher choosing to add a copied question

**Comment by jmdeon** [comment]
Question about @stevoleeto's proposed method of implementation: 
So say teacher1 wants to copy a quiz from teacher2's classroom. Does that mean teacher2 needs to first share the code with teacher1 so that teacher1 can "add by code"?

**Comment by jmdeon** [comment]
Also should a teacher be able to make a fresh copy of one of their own quizzes?

**Comment by stevoleeto** [comment]
That's how I assume it would need to happen, but raises a good question for @sguthals - how do you imagine it working out?

Yes - a teacher should be able to copy their own classes, quizzes, or questions for themselves as well.

**Comment by stevoleeto** [comment]
Progress can be seen on the copyObjects branch
https://github.com/sguthals/OSF/tree/copyObjects

**Comment by stevoleeto** [comment]
Pull request https://github.com/sguthals/OSF/pull/37 solves this
