### ISSUE TITLE
Duplicate Images in Scrambled Answer when refresh

### ISSUE THREAD

**Issue by stevoleeto** [sguthals/OSF#15]
When refreshing the page, the scrambled answer on the left will be completely repopulated. This will cause duplicates to appear (any images in the current answer on the right will again appear in the scrambled answer on the left).

**Comment by stevoleeto** [comment]
+ mark images in answer (on the right) when decoding so that they are not displayed in the scrambled answer (on the left)

**Comment by Saebyuckbaan** [comment]
Fixed it from last pull request
