### ISSUE TITLE
Login Session Bug

### ISSUE THREAD

**Issue by stevoleeto** [sguthals/OSF#21]
Bug Report: Was unable to login to already being logged into a valid session, but unable to sign out of the current session.

**Comment by sguthals** [comment]
Issue:
Unable to login because the app thinks you're already logged in, but no way of forcing a logout.

Tested on Jan 26th and was able to signup and login with a new account. But still unable to login.

**Comment by sguthals** [comment]
Tested on Jan 26th:
Tried to login with sarah@guthals.com and it didn't work. 
Signed up with sarah@sarah.sarah and I was able to login.
Logged out of sarah@sarah.sarah.
Tried to login again with sarah@guthals.com and it still didn't work. 
Tried to login again with sarah@sarah.sarah and it did work.

**Comment by sguthals** [comment]
NVM - the above issue is because the DB was reset and sarah@guthals.com is not a user. 

Stephen still knows of an issue involving cookies, but we cannot recreate right now.

**Comment by sguthals** [comment]
It could be that Devise has an error with their user_signed_in? helper, which is seen here:

> To verify if a user is signed in, use the following helper:
> 
> user_signed_in?

https://github.com/plataformatec/devise/blob/a9bb7d0318054ebb74d09d835927fbb377afd8bd/README.md

But I can't find the actual implementation of it...

**Comment by stevoleeto** [comment]
BUG DETAILS

Sign up for an account, try to sign up again but cannot access sign up page and am redirected to homepage.

**Comment by stevoleeto** [comment]
"Filter chain halted as :require_no_auth rendered or redirected"

**Comment by stevoleeto** [comment]
Pull request https://github.com/sguthals/OSF/pull/38 fixes this
