### ISSUE TITLE
Cannot display more than 4 classes in Classroom view

### ISSUE THREAD

**Issue by jmdeon** [sguthals/OSF#33]

**Comment by Saebyuckbaan** [comment]
Hello, I am Davis, who implemented this part.
I know I am not supposed to bother your work, but here is some hint you can take.

This part can be deleted.
Populate and display first four recent tile was the original decision last year.
/app/views/teacher_classroom/index.html.erb line #10 ~ line 50

I do not think I have implemented this on the student view.

Sincerely,
Davis Yi

**Comment by stevoleeto** [comment]
@Saebyuckbaan Yeah I saw that, since it was such a simple fix I went ahead and pushed it. The specific commit can be found below.

https://github.com/sguthals/OSF/commit/efe49556fb198fdb560aca64f603b42eef4793e7

**Comment by stevoleeto** [comment]
Needs confirmation that issue has been fixed so that it can be closed.
