### ISSUE TITLE
Question encoding/decoding

### ISSUE THREAD

**Issue by Saebyuckbaan** [sguthals/OSF#6]
Encoding and Decoding  function is not work at all in the Questions.js file

**Comment by Saebyuckbaan** [comment]
Currently working on re-writing.
I was expecting this is easier to modify existing code, but existing code has HUGE CORNERCASE.

Current Code:
1. Encode answers in to linear format (Array)
   Problem : 
    Loop
     |-- While - (1) (2) (3)
     Generates [ "Loop", "While" , (1), (2), (3) ];

    Loop
    While - (1) (2) (3)
    ALSO Generates [ "Loop", "While" , (1), (2), (3) ];

They are not same answer.

I am **currently** working on encoding form in to the multi level array like hash chaining.

**Comment by sguthals** [comment]
Because Davis made this a template, now with student answers all we have to do is compare the strings, not iterate through the nested arrays to compare.

- Improving it to make it simpler and more consistent.

**Comment by sguthals** [comment]
A decode function needs to be made for students. It should be different than the one for teachers.

**Comment by Saebyuckbaan** [comment]
Pull request has been made!

**Comment by Saebyuckbaan** [comment]
Update: I talked with my brother( Full stack engineer), and he told me that JSON object is creating random order. (not guarantee the order of the object)

Depends on the computer 
object: {
 a: 10,
 b: 20
};

or 

object: {
  b:20,
  a:10
}.

If the object is more complex, everyone will have a different  look of the encoded answer.
Fortunately, I found the way to guarantee the object order!
