### ISSUE TITLE
Image delete action

### ISSUE THREAD

**Issue by Saebyuckbaan** [sguthals/OSF#7]
When teacher is editing(creating) questions, there is no way to delete images that uploaded alread.
1. I have question images
2. I need delete feature

**Comment by sguthals** [comment]
This should be done by this week.

**Comment by stevoleeto** [comment]
Backend Portion Done. 

Refer to pull #17 with how to use.
https://github.com/sguthals/OSF/pull/17

**Comment by Saebyuckbaan** [comment]
I need to work on the context menu that can allow only "TEACHER" can delete

**Comment by Saebyuckbaan** [comment]
pull request created
